# Generated by Django 4.2.7 on 2025-06-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RiskZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la zone')),
                ('type', models.CharField(choices=[('innondations', 'Inondations'), ('secheresse', 'Sécheresse'), ('glissement de terrain', 'Glissement de terrain')], max_length=50, verbose_name='Type de risque')),
                ('description', models.TextField(verbose_name='Description')),
                ('coordinates', models.JSONField(help_text='Coordonnées du polygone au format GeoJSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Zone à risque',
                'verbose_name_plural': 'Zones à risque',
                'ordering': ['-created_at'],
            },
        ),
    ]
