# Generated by Django 4.2.7 on 2025-06-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskzone',
            name='type',
            field=models.CharField(choices=[('innondations', 'Inondations'), ('secheresse', 'Sécheresse'), ('glissement de terrain', 'Glissement de terrain'), ("cours d'eau", "Cours d'eau")], max_length=50, verbose_name='Type de risque'),
        ),
    ]
