# Generated by Django 5.1 on 2025-06-13 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0002_alter_riskzone_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskzone',
            name='type',
            field=models.CharField(choices=[('innondations', 'Inondations'), ('secheresse', 'Sécheresse'), ('glissement de terrain', 'Glissement de terrain'), ("cours d'eau", "Cours d'eau"), ('zone agricole', 'Zone agricole')], max_length=50, verbose_name='Type de risque'),
        ),
    ]
