# Generated by Django 4.2.7 on 2025-06-13 20:47

from django.db import migrations, models
import django.db.models.deletion
import zones.models


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0002_alter_riskzone_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskzone',
            name='type',
            field=models.CharField(choices=[('innondations', 'Inondations'), ('secheresse', 'Sécheresse'), ('glissement de terrain', 'Glissement de terrain'), ("cours d'eau", "Cours d'eau"), ('zone agricole', 'Zone agricole')], max_length=50, verbose_name='Type de risque'),
        ),
        migrations.CreateModel(
            name='RiskZoneImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=zones.models.zone_image_upload_path, verbose_name='Image')),
                ('caption', models.CharField(blank=True, max_length=255, null=True, verbose_name='Légende')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('risk_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='zones.riskzone', verbose_name='Zone à risque')),
            ],
            options={
                'verbose_name': 'Image de zone à risque',
                'verbose_name_plural': 'Images de zones à risque',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
