# Generated by Django 5.1 on 2025-06-13 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0003_alter_riskzone_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskZoneImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='zones.riskzone')),
            ],
        ),
    ]
