# Generated by Django 4.2.7 on 2025-06-23 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0003_alter_riskzone_type_riskzoneimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskzone',
            name='type',
            field=models.CharField(choices=[('innondations', 'Inondations'), ('secheresse', 'Sécheresse'), ('glissement de terrain', 'Glissement de terrain'), ("cours d'eau", "Cours d'eau"), ('zone agricole', 'Zone agricole'), ('centres de santé', 'Centres de santé'), ('apparition des insectes nuisibles', 'Apparition des insectes nuisibles')], max_length=50, verbose_name='Type de risque'),
        ),
    ]
