# Generated by Django 5.1 on 2025-06-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0004_riskzoneimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskzoneimage',
            name='image',
            field=models.ImageField(upload_to='zone_image/'),
        ),
    ]
