# Generated by Django 5.1 on 2025-06-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0006_alter_riskzoneimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskzoneimage',
            name='image',
            field=models.ImageField(upload_to='image/'),
        ),
    ]
